{{- include "lumigator.openai-default-secret" . -}}
{{- if .Values.openaiAPIKey -}}
{{- if .Values.existingOpenaiAPISecret -}}
{{- fail "A OpenAI key and an existing OpenAI Secret name cannot be provided at the same time" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lumigator.openai-secret-name" . }}
  labels:
    {{- include "lumigator.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Consts.openaiSecretKey }}: {{ .Values.openaiAPIKey | b64enc | quote }}
{{- end -}}
