name: Documentation - Build and publish

on:
  push:
    branches:
        - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Docs - Build and publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for modified paths
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          docs_changes:
            - 'docs/**'

    - name: Check links
      if: steps.filter.outputs.docs-changes == 'true'
      id: lychee
      uses: lycheeverse/lychee-action@v2
      with:
        # Documentation: https://github.com/lycheeverse/lychee?tab=readme-ov-file#commandline-parameters
        args: --base . --verbose --no-progress './**/*.md'  './**/*.rst' --exclude 'mailto:|localhost'

    - name: Set up Python 3.11
      if: steps.filter.outputs.docs_changes == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Set up environment
      if: steps.filter.outputs.docs_changes == 'true'
      id: setup
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV
      continue-on-error: false

    - name: Install docs dependencies
      if: steps.filter.outputs.docs_changes == 'true'
      id: install_build_dependencies
      run: |
        . .venv/bin/activate
        uv pip install -r pyproject.toml --extra docs
      continue-on-error: false

    - name: Build documentation
      if: steps.filter.outputs.docs_changes == 'true'
      run: |
        . .venv/bin/activate
        cd docs
        sphinx-build source build/html

    - name: Set up pages
      if: steps.filter.outputs.docs_changes == 'true'
      uses: actions/configure-pages@v4

    - name: Upload artifact
      if: steps.filter.outputs.docs_changes == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html/

    - name: Deploy
      if: steps.filter.outputs.docs_changes == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
