name: Lumigator backend tests

on:
  push:

jobs:
  uv-example:
    name: Integration tests - Python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        run: uv python install
        working-directory: lumigator/python/mzai/backend

      - name: Lint
        run: uvx ruff check --config ruff.toml
        continue-on-error: false

      - name: Start backend
        run: make start-lumigator-build

      - name: Run tests
        run: SQLALCHEMY_DATABASE_URL=sqlite:///local.db uv run pytest
        working-directory: lumigator/python/mzai/backend

      - name: Stop backend
        run: make stop-lumigator
