name: SDK Tests

on:
  push:

jobs:
  uv-example:
    name: SDK tests - Python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        run: uv python install
        working-directory: lumigator/python/mzai/sdk

      - name: Run tests
        run: uv run pytest
        working-directory: lumigator/python/mzai/sdk
